# Generated by Django 5.2.7 on 2025-10-16 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inondation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_incident', models.CharField(blank=True, default='', max_length=100)),
                ('location_text', models.CharField(blank=True, default='', max_length=255)),
                ('severity', models.CharField(blank=True, default='', max_length=20)),
                ('description', models.TextField()),
                ('prenom', models.CharField(blank=True, default='', max_length=100)),
                ('nom', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alerte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inondation.alerte')),
                ('localisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inondation.localisation')),
            ],
        ),
        migrations.CreateModel(
            name='SignalementPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='signalements/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inondation.signalement')),
            ],
        ),
    ]
