# Generated by Django 5.2.7 on 2025-11-06 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inondation', '0003_signalement_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_text', models.CharField(max_length=255)),
                ('help_type', models.CharField(max_length=100)),
                ('people_count', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=50)),
                ('availability', models.CharField(blank=True, default='', max_length=100)),
                ('urgency_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistance_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Degat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=100)),
                ('loss_amount_text', models.CharField(blank=True, default='', max_length=100)),
                ('loss_description', models.TextField(blank=True, default='')),
                ('people_affected', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DegatPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='degats/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('degat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='inondation.degat')),
            ],
        ),
    ]
